/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseRequestRouteImport } from './routes/useRequest'
import { Route as TanstackQueryRouteImport } from './routes/tanstackQuery'

const UseRequestRoute = UseRequestRouteImport.update({
  id: '/useRequest',
  path: '/useRequest',
  getParentRoute: () => rootRouteImport,
} as any)
const TanstackQueryRoute = TanstackQueryRouteImport.update({
  id: '/tanstackQuery',
  path: '/tanstackQuery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/tanstackQuery': typeof TanstackQueryRoute
  '/useRequest': typeof UseRequestRoute
}
export interface FileRoutesByTo {
  '/tanstackQuery': typeof TanstackQueryRoute
  '/useRequest': typeof UseRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/tanstackQuery': typeof TanstackQueryRoute
  '/useRequest': typeof UseRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tanstackQuery' | '/useRequest'
  fileRoutesByTo: FileRoutesByTo
  to: '/tanstackQuery' | '/useRequest'
  id: '__root__' | '/tanstackQuery' | '/useRequest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TanstackQueryRoute: typeof TanstackQueryRoute
  UseRequestRoute: typeof UseRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/useRequest': {
      id: '/useRequest'
      path: '/useRequest'
      fullPath: '/useRequest'
      preLoaderRoute: typeof UseRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tanstackQuery': {
      id: '/tanstackQuery'
      path: '/tanstackQuery'
      fullPath: '/tanstackQuery'
      preLoaderRoute: typeof TanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TanstackQueryRoute: TanstackQueryRoute,
  UseRequestRoute: UseRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
